import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'

import {ReactNode} from "react";
import StyledComponentsRegistry from "@/app/lib/registry";
// import {Side_bar} from "@/components/side_bar/side_bar";


const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create next app',
}
interface RootLayoutProps {
    children: ReactNode;
}
export default function RootLayout({children,}: RootLayoutProps) {
    return (
        <html lang="en">
        <body className={inter.className}>
            <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </body>
        </html>
    )
}
